export const REQUEST_CART = 'REQUEST_CART'
export const RECEIVE_CART = 'RECEIVE_CART'
export const REQUEST_QUESGROUP = 'REQUEST_QUESGROUP'
export const RECEIVE_QUESGROUP = 'RECEIVE_QUESGROUP'

export const REQUEST_ANSWER = 'REQUEST_ANSWER'
export const RECEIVE_ANSWER = 'RECEIVE_ANSWER'

export const REQUEST_PAGE = 'REQUEST_PAGE'
export const RECEIVE_PAGE = 'RECEIVE_PAGE'


export const REQUEST_QUE = 'REQUEST_QUE'
export const RECEIVE_QUE = 'RECEIVE_QUE'
