export const CAN_SUBMIT ='CAN_SUBMIT'
export const TOGGLE_SHOW_CART   = 'TOGGLE_SHOW_CART'
export const TOGGLE_SHOW_ALERT   = 'TOGGLE_SHOW_ALERT'
export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'
export const SET_SLICK_ORIENTATION = 'SET_SLICK_ORIENTATION'
export const HAS_VISITED = 'HAS_VISITED'

export const ADD_TIME = 'ADD_TIME'
export const ADD_SINGLE_ANSWER = 'ADD_SINGLE_ANSWER'
export const ADD_SUB_SINGLE_ANSWER = 'ADD_SUB_SINGLE_ANSWER'
export const ADD_ANSWER_REMOVE_REPEAT = 'ADD_ANSWER_REMOVE_REPEAT'

export const ADD_ANSWER = 'ADD_ANSWER'
export const ADD_SUB_ANSWER = 'ADD_SUB_ANSWER'


export const DELETE_ANSWER = 'DELETE_ANSWER'
export const DELETE_SUB_ANSWER = 'DELETE_SUB_ANSWER'

export const TOGGLE_ADD_ANSWER = 'TOGGLE_ADD_ANSWER'
export const TOGGLE_ADD_SUB_ANSWER = 'TOGGLE_ADD_SUB_ANSWER'


export const ADD_DONE_COUNT = 'ADD_DONE_COUNT'
export const ADD_ANSWER_PUSH = 'ADD_ANSWER_PUSH'
export const ADD_SUB_ANSWER_PUSH = 'ADD_SUB_ANSWER_PUSH'

export const DELETE_ANSWER_SPLICE = 'DELETE_ANSWER_SPLICE'
export const DELETE_SUB_ANSWER_SPLICE ='DELETE_SUB_ANSWER_SPLICE'
